from services.betting_service import BettingService
from services.game_session_manager import GameSessionManager
from services.win_loss_calculator import WinLossCalculator
from tracking_and_reports.win_loss_statistics import WinLossStatistics
from tracking_and_reports.gambler_statistics import GamblerStatistics
from utils.input_validator import InputValidator
from ui.game_status_display import GameStatusDisplay
from ui.session_summary import SessionSummaryDisplay

class InteractiveGameplay:
    def __init__(self):
        self.bet_service = BettingService()
        self.session_manager = GameSessionManager()
        self.win_loss_calc = WinLossCalculator()
        self.stats = WinLossStatistics()
        self.gambler_stats = GamblerStatistics()
        self.validator = InputValidator()

    def run_table(self, gambler_id: int, session_id: int):
        """Runs the active interactive gameplay loop."""
        print("\nWelcome to the Table! Setting up your session...")
        
        while True:
            # 1. Fetch current status
            summary = self.session_manager.get_session_summary(session_id)
            if not summary or summary['session']['status'] != 'ACTIVE':
                print("Session is no longer active.")
                break
                
            session = summary['session']
            profile = self.gambler_stats.get_profile_summary(gambler_id)['gambler']
            
            # 2. Display Dashboard
            GameStatusDisplay.show_dashboard(
                gambler_name=profile['username'],
                current_stake=session['ending_stake'] or session['peak_stake'], # Fallback to peak if active
                lower_limit=session['lower_limit'],
                upper_limit=session['upper_limit'],
                games_played=session['games_played']
            )
            
            # 3. Action Prompt
            print("Options: [P]lace Bet | [S]uspend/Pause | [E]nd Session")
            action = input("Your move: ").upper()
            
            if action == 'E':
                self.session_manager.end_session(session_id, "MANUAL")
                break
            elif action == 'S':
                reason = input("Reason for pausing: ")
                self.session_manager.pause_session(session_id, reason)
                print("Session paused. Returning to menu...")
                return # Exit back to UC-07 router
                
            elif action == 'P':
                try:
                    bet_amt = float(input("Enter Bet Amount: "))
                    
                    # Basic Validation Hook
                    val_result = self.validator.validate_bet(
                        bet_amt, 
                        profile['current_stake'], 
                        min_bet=session['min_bet'] if 'min_bet' in session else 1, 
                        max_bet=session['max_bet'] if 'max_bet' in session else 10000
                    )
                    if not val_result.is_valid:
                        for msg in val_result.messages:
                            print(f"{msg.message}")
                        continue
                        
                    # 4. Place and Resolve Bet
                    # Using a simple coin flip (50/50, 2.0x payout) for the UI demo
                    bet_id = self.bet_service.place_bet(gambler_id, bet_amt, win_probability=0.5, odds_value=2.0)
                    res = self.bet_service.resolve_bet(bet_id)
                    
                    # 5. Show Outcome
                    payout_or_loss = res['payout'] if res['outcome'] == 'WIN' else bet_amt
                    GameStatusDisplay.show_outcome(res['outcome'], payout_or_loss, res['new_balance'])
                    
                    # 6. Update Analytics
                    # Find the Game ID generated by the resolve process
                    history = self.bet_service.get_bet_history(gambler_id)
                    latest_game_id = history[0]['bet_id'] # Approximating game ID map for UI speed
                    self.win_loss_calc.update_running_totals(session_id, latest_game_id)
                    
                    # 7. Check Boundaries (Auto-End)
                    boundary_status = self.session_manager.check_boundaries(session_id)
                    if boundary_status != "OK":
                        print(f"Session Auto-Ended! Reason: {boundary_status}")
                        break
                        
                except ValueError:
                    print("Invalid input. Please enter numbers only.")
                except Exception as e:
                    print(f"Transaction Failed: {e}")

        # 8. Out of Loop -> Show Final Summary
        print("\nGenerating Final Report...")
        final_summary = self.session_manager.get_session_summary(session_id)
        final_stats = self.stats.get_latest_session_stats(session_id)
        SessionSummaryDisplay.print_final_report(final_summary, final_stats)